export const images = [
    { id: 1,name:"Manchester City", src: "https://logodetimes.com/times/manchester-city/logo-manchester-city-4096.png", alt: "Image 1" },
    { id: 2,name:"Girona Fc", src: "https://statics-maker.llt-services.com/gir/images/2024/02/05/original/ec06d70b-44be-4189-a646-cf5bd991bfd2-112.png", alt: "Image 2" },
    { id: 3, name:"Atletico Madrid", src: "https://en.atleticodemadrid.com/images/EscudoATM.svg", alt: "Image 3" },
    { id: 4, name:"Sporting Lisbon", src: "https://upload.wikimedia.org/wikipedia/en/e/e1/Sporting_Clube_de_Portugal_%28Logo%29.svg", alt: "Image 4" },
    { id: 5, name:"Celtic Glasgow", src: "https://upload.wikimedia.org/wikipedia/en/7/71/Celtic_FC_crest.svg", alt: "Image 5" },
    { id: 6, name:"Bayern Munich", src: "https://upload.wikimedia.org/wikipedia/commons/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg", alt: "Image 6" },
    { id: 7, name:"Bayer Leverkusen", src: "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg", alt: "Image 7" },
    { id: 8, name:"Inter Milan", src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/800px-FC_Internazionale_Milano_2021.svg.png", alt: "Image 8" },
    { id: 9, name:"Liverpool", src: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg", alt: "Image 9" },
    { id: 10, name:"Ac Milan", src: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg", alt: "Image 10" },
    { id: 11, name:"Arsenal", src: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg", alt: "Image 11" },
    { id: 12, name:"Manchester United", src: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/200px-Manchester_United_FC_crest.svg.png", alt: "Image 12" },
    { id: 13, name:"Real Sociedad", src: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Real_Sociedad_logo.svg/154px-Real_Sociedad_logo.svg.png?20130502223536", alt: "Image 13" },
    { id: 14, name:"Inter Miami", src: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Inter_Miami_CF_logo.svg/800px-Inter_Miami_CF_logo.svg.png", alt: "Image 14" },
    { id: 15, name:"Chelsea", src: "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg", alt: "Image 15" },
    { id: 16, name:"Athletic Bilbao", src: "https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg", alt: "Image 16" },
    { id: 17, name:"Ajax Amsterdam", src: "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/Ajax_Amsterdam.svg/306px-Ajax_Amsterdam.svg.png?20070907021558", alt: "Image 17" },
    { id: 18, name:"Newcastle United", src: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/300px-Newcastle_United_Logo.svg.png?20160318235642", alt: "Image 18" },
    { id: 19, name:"West Ham United", src: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/169px-West_Ham_United_FC_logo.svg.png?20170924185552", alt: "Image 19" },
    { id: 20, name:"Al Nassr", src: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Al_Nassr_FC_Logo.svg/800px-Al_Nassr_FC_Logo.svg.png", alt: "Image 20" },
    { id: 21, name:"Real Batis", src: "https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg", alt: "Image 21" },
    { id: 22, name:"Osasuna Fc", src: "https://upload.wikimedia.org/wikipedia/en/3/38/CA_Osasuna_2024_crest.svg", alt: "Image 22" },
    { id: 23, name:"Real Madrid", src: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg", alt: "Image 23" },
    { id: 24, name:"Fc Barcelona", src: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg", alt: "Image 24" },
    { id: 25, name:"Dortmund", src: "https://logodownload.org/wp-content/uploads/2017/02/bvb-borussia-dortmund-logo-1.png", alt: "Image 25" },
    { id: 26, name:"Al Hilal", src: "https://logodetimes.com/times/al-hilal/al-hilal-2023-2048.png", alt: "Image 26" },
    { id: 27, name:"Rb Leipzig", src: "https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg", alt: "Image 27" },
    { id: 28, name:"Al Fateh", src: "https://th.bing.com/th/id/R.6c15f0dde9ac9b1fae9e1ea5fab2b01d?rik=MQA1aZLHprId6Q&pid=ImgRaw&r=0", alt: "Image 28" },
    { id: 29, name:"PSG", src: "https://logodownload.org/wp-content/uploads/2017/02/psg-logo-escudo-paris-saint-germain.png", alt: "Image 29" },
    { id: 30,name:"Al Riyadh", src: "https://cdn.resfu.com/img_data/equipos/17271.png", alt: "Image 30" },
    { id: 31,name:"Atalanta BC", src: "https://upload.wikimedia.org/wikipedia/en/thumb/6/66/AtalantaBC.svg/253px-AtalantaBC.svg.png?20220130173653", alt: "Image 31" },
    { id: 32,name:"Udinese Calcio", src: "https://logodownload.org/wp-content/uploads/2020/10/udinese-logo-1.png", alt: "Image 32" },
  ];